### PR TITLE
Workshop fix

### PR DESCRIPTION
**Pull request by briangerard**
Some tweaks found during the workshop on 2017/10/21.

### CODE REVIEW

**Comment by jbelmont** [comment]
Awesome thanks Brian

**Comment by jbelmont** [comment]
Brian I am following you in Github now can you follow me, I would like to keep in sync with you via Github.

**Comment by jbelmont** [comment]
My github handle is jbelmont so you can follow

**Comment by briangerard** [comment]
Done - following you.  :-)

**Comment by jbelmont** [comment]
Cool thanks my friend.

**Pull request merged**
